### PR TITLE
translate some of neural_network (#18)

### PR DESCRIPTION
**Pull request by rickiepark**
Please verify this work.
Next time, I'll pull request whole document.
Thanks.

### CODE REVIEW

**Comment by genekogan** [comment]
awesome! do you think it's ready? if so, i will link to it from the main page and tweet it

**Comment by rickiepark** [comment]
It's better when next pull request is merged. :)

**Comment by genekogan** [comment]
great! by the way i think you accidentally removed the header which has the data for how the main page can find it. i put that back in. maybe you can also translate the quote up there by ada lovelace and the title?

**Comment by rickiepark** [comment]
Oops! it's my mistake. I just removed it for markdown printing. :(

Yes, I'll translate the title and ada story. :)

**Pull request merged**
